### ISSUE TITLE
libbz2-rs-sys v0.1.1 requires Rust 1.82

### ISSUE THREAD

**Issue by martin-g** [trifectatechfoundation/bzip2-rs#119]
Hello,

https://github.com/trifectatechfoundation/bzip2-rs/releases/tag/v0.5.0 says:
```
The 0.5.0 release is the first release in ~2 years. It sets an msrv of 1.65.0 and pins the 2021 edition. If the msrv or edition are a problem for your project: just stick with the 0.4.4 release.
```

I tried to build with 1.74 and I got this error:
```
error: package `libbz2-rs-sys v0.1.1` cannot be built because it requires rustc 1.82 or newer, while the currently active rustc version is 1.74.0
Either upgrade to rustc 1.82 or newer, or use
cargo update libbz2-rs-sys@0.1.1 --precise ver
where `ver` is the latest version of `libbz2-rs-sys` supporting rustc 1.74.0
```
Full logs at https://github.com/apache/avro-rs/actions/runs/12293251964/job/34305569034?pr=77

The dependabot PR - https://github.com/apache/avro-rs/pull/77

**Comment by NobodyXu** [comment]
It seems that libbz2-rs-sys is enabled, which pulls in a pure-rust bzip2 impl that requires 1.82?

**Comment by martin-g** [comment]
Yes, I enabled that feature because otherwise the upgrade from 0.4 to 0.5 failed with:
```
error[E0463]: can't find crate for `bzip2_sys`
  --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bzip2-0.5.0/src/lib.rs:60:1
   |
60 | extern crate bzip2_sys as ffi;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
```
https://github.com/apache/avro-rs/actions/runs/12289804123/job/34295892925

**Comment by martin-g** [comment]
Thanks for the pointer, @NobodyXu !
The problem was that we disable `default` features and explicitly list only the needed ones - https://github.com/apache/avro-rs/blob/4e055480520499c0b6d3ce4b9fbfec7b9950b843/avro/Cargo.toml#L58

The error message and the release notes made me think that I need to add `libbz2-rs-sys` feature, while I needed the `default` one. Now the build passes!

I think that it would be a good idea to mention that `libbz2-rs-sys` requires 1.82 in the release notes.

Thank you!
